service: KolkataBusApi
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 2048
  stage: dev
  timeout: 30
  region: ap-south-1
  lambdaHashingVersion: 20201221

functions: 
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /     
    environment:
      MONGO_URL: mongodb+srv://kbopofficial:W5rzqYJGeD0fbm2y@kolkatabus.jtdjj.mongodb.net/?retryWrites=true&w=majority&appName=kolkataBus
      SECRET_KEY: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiYmQ3NmQ1MWNhMmFlZTRiYmYzNGU0OGM5OWJhZDg2YiIsIm5iZiI6MTcyMjE2Nzg1OS4yOTA1MjUsInN1YiI6IjY2YTUwODRhYTgwMjNhNjUyMTllYzU3MyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.65zvD6XGblbWVqukkzjNu2viV5vRK60tKy26Rxybmus

